---
- name: "print out thr facts that where set using hostvars param" 
  hosts: junos
  connection: local
  vars:
    - dir_path: result
    - allhosts: "{{hostvars}}"
  tasks:
    - name: "get routing engine cpu information "
      junos_command:
       commands: show version | display xml 
      register: cmd_result

    - set_fact:
        out_hostname: "{{ cmd_result.output[0]['rpc-reply']['software-information']['host-name'] }}"
        out_version: "{{ cmd_result.output[0]['rpc-reply']['software-information']['package-information']['comment'] }}"
        out_model: "{{ cmd_result.output[0]['rpc-reply']['software-information']['product-model'] }}"

    - debug: var=allhosts[inventory_hostname]['out_model']
    - debug: var=allhosts['192.168.20.243']['out_model']
    - debug: var=allhosts['192.168.20.243'].out_model
    

    